import type { Metadata } from "next";
import "./globals.css";
import { Libre_Caslon_Text } from "next/font/google"

const caslon = Libre_Caslon_Text({
  weight: ["400", "700"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${caslon.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
